
#Date: April 15, 2024

#Pre-processing of feature data
#mRNA and protein levels from GTEx (eGTEx)
#Tissue-specific
#GTEx data comparison (Using different type of data for gene expression and protein abundance & comparison)

packages <- c(
  "openxlsx", "dplyr", "ggplot2", "factoextra", "reshape2"
)

installed <- rownames(installed.packages())
for (pkg in packages) {
  if (!pkg %in% installed) {
    install.packages(pkg, dependencies = TRUE)
  }
}

lapply(packages, library, character.only = TRUE)

info_path <- "./Data/GTEX_tissuenames_tcganames.xlsx"
gtex_protein_path <- "./Downloads/Table_S1_gene_info_at_protein_level.xlsx"
gtex_mrna_path <- "./Downloads/Table_S2_gene_info_at_RNA_level.xlsx"
gene_ID_name_path <- "./Downloads/Table_S1_gene_info_at_protein_level.xlsx"
tissuenames_tcganames_path <- "./Data/eGTEX_tissuenames_tcganames.xlsx"
gtex_protein_tissue_median_path <- "./Data/eGTEX_mrna_protein_tissue_median.RData"
gene_info_protein_level <- "./Downloads/Table_S1_gene_info_at_protein_level.xlsx"
gtex_v6_RNA_median_path <- "./Downloads/GTEx_Analysis_v6p_RNA-seq_RNA-SeQCv1.1.8_gene_median_rpkm.gct"
mrna_v8_path <- "./Downloads/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct"
gtex_outpath <- "./Data/GTEx_different_versions_TCGA_cohort_map.RData"
tissue_specific_genes_v8 <- "./Data/Tissue_specific_genes_based_on_GTEx_v8.RData"
tissue_specific_proteins_path <- "./Downloads/Table_S1_gene_info_at_protein_level.xlsx"
tissuespec_proteins <- "./Data/Tissue_specific_proteins_based_on_eGTEx_TSscore.RData"
gtex_adult_v8_path <- "./Downloads/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct"
CORUM_feat_tissue_general_path <- "./Data/Ensembl_CORUM_features_tissue_general.RData"


#GTEx-TCGA tissue mapping for all versions of GTEx

# #Adult GTEx (Only mRNA level quantification)
# #GTEx Release V6p and V7: Genome version GRCh37/hg19
# mrna.v6p <- read.delim("./Downloads/GTEx_Analysis_v6p_RNA-seq_RNA-SeQCv1.1.8_gene_median_rpkm.gct",skip = 2)
# mrna.v6p$Name <- unlist(lapply(mrna.v6p$Name, function(x) gsub("\\..*","",x)))
# mrna.v7 <- read.delim("./Downloads/GTEx_Analysis_2016-01-15_v7_RNASeQCv1.1.8_gene_median_tpm.gct",skip = 2)
# mrna.v7$gene_id <- unlist(lapply(mrna.v7$gene_id, function(x) gsub("\\..*","",x)))
# save(mrna.v6p, mrna.v7, file = "./Data/GTEX_tissue_median.RData")
# #Adding additional tissue names to the information table
# info.gtex <- data.frame("V6p" = colnames(mrna.v6p)[-c(1,2)],
#                         "V7" = colnames(mrna.v7)[-c(1,2)])
# write.xlsx(info.gtex, file = info_path) #eGTEx tissuenames & tcganames were added to the this file (manualy).

info <- read.xlsx(info_path,startRow = 2)
datasets <- list()

#Dataset 1: eGTEx

#Enhancing GTEx (eGTEx) (normal tissue)
#Protein and RNA expression levels in 32 normal human tissues were downloaded from Enhancing GTEx (eGTEX) for matched samples
#Data was obtained from GTEx. The same table as in the original publication (mmc2.xlsx) https://pubmed.ncbi.nlm.nih.gov/32916130/
#The proteomics data was generated by TMT-MS3 based quantitative mass spectrometry.
#The RNA-seq data in Transcripts Per Kilobase Million (TPM) were obtained from the GTEx portal in version 8 based on the GENCODE v26.

gtex.protein <- read.xlsx(gtex_protein_path,sheet = 9) #12627 - Median relative protein abundance in each tissue type
gtex.mrna <- read.xlsx(gtex_mrna_path,sheet = 3) #12245 - Tissue medians at RNA level
#To retrieve gene symbols for gene IDs
geneID_name <- read.xlsx(gene_ID_name_path,sheet = 10)
gtex.protein <- merge(geneID_name[,c(1,4)], gtex.protein, by.x="ensembl_id",by.y = "gene.id")
gtex.mrna <- merge(geneID_name[,c(1,4)], gtex.mrna, by.x="ensembl_id",by.y = "gene.id")
#GTEx tissue names and their matching TCGA names
tissue.names <- read.xlsx(gene_info_protein_level,sheet = 12, startRow = 2)
tissue.names <- rbind(tissue.names[,1:2],tissue.names[3:4])
tissue.names$Colnames <- colnames(gtex.protein)[3:34]
write.xlsx(tissue.names, file = tissuenames_tcganames_path)
save(gtex.mrna, gtex.protein, file = gtex_protein_tissue_median_path)

#Optional part I
# rm(list = ls())
# #Checking if tissues (mapping to the same TCGA cohort) are clustered together based on their RNA expression and protein abundance
# #eGTEx
# info <- read.xlsx(info_path,startRow = 2)
# info <- info[,5:6]
# info <- info[complete.cases(info),]
# load(gtex_protein_tissue_median_path)
# #PCA based on RNA expression
# rownames(gtex.mrna) <- gtex.mrna$ensembl_id
# gtex.mrna <- gtex.mrna[,-c(1,2)]
# gtex.mrna <- as.data.frame(t(gtex.mrna))
# gtex.mrna$Colnames <- rownames(gtex.mrna)
# gtex.mrna <- merge(info,gtex.mrna,by="Colnames")
# gtex.mrna$Colnames <- paste(gtex.mrna$Colnames,as.character(seq(1,22)),sep=".")
# rownames(gtex.mrna) <- gtex.mrna$Colnames
# df.pca <- gtex.mrna[,-c(1,2)]
# df.pca[is.na(df.pca)] <- 0
# res.pca <- prcomp(df.pca, scale = FALSE)
# groups <- as.factor(gtex.mrna$TCGA)
# fviz_pca_ind(res.pca,
#              geom = c("point","text"),
#              col.ind = groups, # color by groups
#              legend.title = "TCGA cohorts",
#              repel = TRUE,
#              title = "eGTEx mRNA expressions")
# #PCA based on protein abundance
# rownames(gtex.protein) <- gtex.protein$ensembl_id
# gtex.protein <- gtex.protein[,-c(1,2)]
# gtex.protein <- as.data.frame(t(gtex.protein))
# gtex.protein$Colnames <- rownames(gtex.protein)
# gtex.protein <- merge(info,gtex.protein,by="Colnames")
# gtex.protein$Colnames <- paste(gtex.protein$Colnames,as.character(seq(1,22)),sep=".")
# rownames(gtex.protein) <- gtex.protein$Colnames
# df.pca <- gtex.protein[,-c(1,2)]
# df.pca[is.na(df.pca)] <- 0
# res.pca <- prcomp(df.pca, scale = FALSE)
# groups <- as.factor(gtex.protein$TCGA)
# fviz_pca_ind(res.pca,
#              geom = c("point","text"),
#              col.ind = groups, # color by groups
#              legend.title = "TCGA cohorts",
#              repel = TRUE,
#              title = "eGTEx protein abundance")

#Taking median to prepare TCGA cohort level data
rm(list = setdiff(ls(),c("info","datasets")))

load(gtex_protein_tissue_median_path)

rownames(gtex.mrna) <- gtex.mrna$ensembl_id
m <- as.data.frame(t(gtex.mrna[,-c(1,2)]))
m$Colnames <- rownames(m)
m <- merge(info[,5:6],m,by="Colnames")
m <- m[complete.cases(m$TCGA),]
m <- m %>% group_by(TCGA) %>% summarise(across(where(is.numeric), ~ median(.x, na.rm = TRUE)))
m <- as.data.frame(m)
rownames(m) <- m$TCGA
m <- as.data.frame(t(m[,-1]))
m$Gene.stable.ID <- rownames(m)
m <- merge(gtex.mrna[,1:2],m,by.x = "ensembl_id" ,by.y = "Gene.stable.ID")
colnames(m)[1:2] <- c("Gene.stable.ID","Gene.name") 
datasets[["eGTEX.rna"]] <- m
#eGTEX protein
rownames(gtex.protein) <- gtex.protein$ensembl_id
m <- as.data.frame(t(gtex.protein[,-c(1,2)]))
m$Colnames <- rownames(m)
m <- merge(info[,5:6],m,by="Colnames")
m <- m[complete.cases(m$TCGA),]
m <- m %>% group_by(TCGA) %>% summarise(across(where(is.numeric), ~ median(.x, na.rm = TRUE)))
m <- as.data.frame(m)
rownames(m) <- m$TCGA
m <- as.data.frame(t(m[,-1]))
m$Gene.stable.ID <- rownames(m)
m <- merge(gtex.protein[,1:2],m,by.x = "ensembl_id" ,by.y = "Gene.stable.ID")
colnames(m)[1:2] <- c("Gene.stable.ID","Gene.name") 
datasets[["eGTEX.protein"]] <- m

rm(list = setdiff(ls(),c("info","datasets")))

#Dataset 2: Adult GTEx (v6)

#Adult GTEx (Only mRNA level quantification)
#GTEx Release V6p and V7: Genome version GRCh37/hg19
mrna.v6p <- read.delim(gtex_v6_RNA_median,skip = 2)
mrna.v6p$Name <- unlist(lapply(mrna.v6p$Name, function(x) gsub("\\..*","",x)))
rownames(mrna.v6p) <- mrna.v6p$Name
m <- as.data.frame(t(mrna.v6p[,-c(1,2)]))
m$V6p <- rownames(m)
m <- merge(info[,c(1,6)],m,by="V6p")
m <- m[complete.cases(m$TCGA),]
m <- m %>% group_by(TCGA) %>% summarise(across(where(is.numeric), ~ median(.x, na.rm = TRUE)))
m <- as.data.frame(m)
rownames(m) <- m$TCGA
m <- as.data.frame(t(m[,-1]))
m$Gene.stable.ID <- rownames(m)
m <- merge(mrna.v6p[,1:2],m,by.x = "Name" ,by.y = "Gene.stable.ID")
colnames(m)[1:2] <- c("Gene.stable.ID","Gene.name")
datasets[["GTEx.v6.RPKM"]] <- m


#Dataset 3:Adult GTEx (v8)

mrna.v8 <- read.delim(mrna_v8_path,skip = 2)
mrna.v8$Name <- unlist(lapply(mrna.v8$Name, function(x) gsub("\\..*","",x)))
gene.info <- mrna.v8[,1:2]
gene.info <- gene.info[!duplicated(gene.info$Name),]
#For duplicated ensembl IDs, keep the maximum
mrna.v8 <- mrna.v8 %>% group_by(Name) %>% summarise(across(where(is.numeric), ~ max(.x, na.rm = TRUE)))
mrna.v8 <- merge(gene.info, mrna.v8, by = "Name")
rownames(mrna.v8) <- mrna.v8$Name
m <- as.data.frame(t(mrna.v8[,-c(1,2)]))
m$V8 <- rownames(m)
m <- merge(info[,c(1,6)],m,by.x="V6p",by.y = "V8")
m <- m[complete.cases(m$TCGA),]
m <- m %>% group_by(TCGA) %>% summarise(across(where(is.numeric), ~ median(.x, na.rm = TRUE)))
m <- as.data.frame(m)
rownames(m) <- m$TCGA
m <- as.data.frame(t(m[,-1]))
m$Gene.stable.ID <- rownames(m)
m <- merge(mrna.v8[,1:2],m,by.x = "Name" ,by.y = "Gene.stable.ID")
colnames(m)[1:2] <- c("Gene.stable.ID","Gene.name")
datasets[["GTEx.v8.TPM"]] <- m

save(datasets, file = gtex_outpath)

#Comparison of gene expressions among different mRNA datasets in GTEx
# load(gtex_outpath)
# common.genes <- intersect(datasets$eGTEX.rna$Gene.stable.ID,
#                           datasets$GTEx.v6.RPKM$Gene.stable.ID)
# common.genes <- intersect(common.genes, datasets$GTEx.v8.TPM$Gene.stable.ID)
# 
# df <- datasets[["eGTEX.rna"]]
# df <- df[df$Gene.stable.ID %in% common.genes,c("Gene.stable.ID","BRCA")]
# colnames(df)[2] <- "eGTEX.rna"
# #Example tissue type: ACC
# for(name in c("GTEx.v6.RPKM","GTEx.v8.TPM")){
#   add.df <- datasets[[name]]
#   add.df <- add.df[add.df$Gene.stable.ID %in% common.genes,c("Gene.stable.ID","BRCA")]
#   colnames(add.df)[2] <- name
#   df <- merge(df,add.df,by="Gene.stable.ID")}
# 
# ggplot(df, aes(x=eGTEX.rna, y=log2(GTEx.v6.RPKM + 0.001))) + geom_point() +
#   theme_bw() + geom_smooth(method=lm, se=FALSE) + stat_cor(method = "pearson")
# 
# ggplot(df, aes(x=eGTEX.rna, y=log2(GTEx.v8.TPM + 0.001))) + geom_point() +
#   theme_bw() + geom_smooth(method=lm, se=FALSE) + stat_cor(method = "pearson")
# 
# ggplot(df, aes(x=GTEx.v6.RPKM, y=GTEx.v8.TPM)) + geom_point() +
#   theme_bw() + geom_smooth(method=lm, se=FALSE) + stat_cor(method = "pearson")

#Correlations are very high (0.99, 0.99, 1)

#Tissue-relative scores (z-scores based on TPM - v8)
m <- datasets$GTEx.v8.TPM
m.scaled <- c()
for(i in 1:nrow(m)){
  v <- as.numeric(m[i,-c(1,2)])
  v.scaled <- as.numeric(scale(v))
  m.scaled <- rbind(m.scaled, c(m$Gene.stable.ID[i],m$Gene.name[i],v.scaled))
  print(i)}
m.scaled <- as.data.frame(m.scaled)
colnames(m.scaled) <- colnames(m)
m.scaled[,3:25] <- sapply(m.scaled[,3:25], as.numeric)
datasets[["scaled.GTEx.v8.TPM"]] <- m.scaled

save(datasets, file = gtex_outpath)

#Tissue-specific genes
#First remove genes less than 1 TPM
#Then filter based on z-score (abs z-score > 2, tissue specific) - using absolute value is different from Uri-Ben David paper (preferential low expression could play a role in selection)
#I did not use eGTEx paper's TS because the number of the genes in RNA data is limited with proteome covarage
load(gtex_outpath)
m <- datasets$GTEx.v8.TPM
zscores <- datasets$scaled.GTEx.v8.TPM
tissue.specific.genes <- list()
cohorts <- colnames(m)[3:25]
for(cohort in cohorts){
  df <- m[,c("Gene.stable.ID","Gene.name",cohort)]
  colnames(df)[3] <- "tpm"
  df <- df[df$tpm > 1,]
  df.scaled <- zscores[,c("Gene.stable.ID","Gene.name",cohort)]
  colnames(df.scaled)[3] <- "zscore"
  df.scaled <- df.scaled[abs(df.scaled$zscore) > 2,]
  genes <- intersect(df$Gene.stable.ID,df.scaled$Gene.stable.ID)
  tissue.specific.genes[[cohort]] <- df[df$Gene.stable.ID %in% genes, 1:2]}

save(tissue.specific.genes, file = tissue_specific_genes_v8)

#Tissue-specific proteins
#Based on TS score in https://www.sciencedirect.com/science/article/pii/S0092867420310783?via%3Dihub - eGTEx paper
gtex.protein.TS <- read.xlsx(tissue_specific_proteins_path,sheet = 11) #12627 - Median relative protein abundance in each tissue type
for(col in 5:ncol(gtex.protein.TS)){
  new.values <- as.numeric(unlist(lapply(gtex.protein.TS[,col], function(x) strsplit(x,";")[[1]][1])))
  gtex.protein.TS[,col] <- new.values}

tissues <- colnames(gtex.protein.TS)[5:ncol(gtex.protein.TS)]

tissue.specific.proteins.tissues <- list()

for(tissue in tissues){
  df <- gtex.protein.TS[,c("ensembl_id","hgnc_symbol",tissue)]
  df <- df[complete.cases(df),]
  colnames(df)[3] <- "tissue"
  df <- df[abs(df$tissue) >= 2.5,]
  df <- df[,1:2]
  colnames(df) <- c("Gene.stable.ID","Gene.name")
  tissue.specific.proteins.tissues[[tissue]] <- df}

#Converting tissue names to TCGA cohorts
info <- read.xlsx(info_path,startRow = 2)
info <- info[,5:6]
info <- info[complete.cases(info),]
tissue.specific.proteins <- list()
for(cohort in unique(info$TCGA)){
  names <- info[info$TCGA == cohort,]$Colnames
  genes <- c()
  for(name in names){
    df <- tissue.specific.proteins.tissues[[name]]
    genes <- rbind(genes,df)}
  genes <- genes[!duplicated(genes$Gene.stable.ID),]
  tissue.specific.proteins[[cohort]] <- genes
}

save(tissue.specific.proteins, file = tissuespec_proteins)

#-------------------------------------
# EXTRA DETAILS
# Date: October 15, 2024
# Understanding (scaled) TPM data

rm(list = ls())
                                         
#Dataset 3:Adult GTEx (v8)
mrna.v8 <- read.delim(gtex_adult_v8_path,skip = 2)
mrna.v8.melt <- melt(mrna.v8)
mrna.v8.melt$log2tpm <- log2(mrna.v8.melt$value + 1)
# Learn from data
medians <- mrna.v8.melt %>% group_by(variable) %>% summarise("Median" = median(log2tpm, na.rm = T))
medians <- medians[order(medians$Median, decreasing = T),]
mrna.v8.melt$variable <- factor(mrna.v8.melt$variable, levels = as.character(medians$variable))
ggplot(mrna.v8.melt, aes(x = variable, y = log2tpm)) + geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


load(gtex_outpath)
tpm <- datasets$scaled.GTEx.v8.TPM
tpm.melted <- melt(tpm)
medians <- tpm.melted %>% group_by(variable) %>% summarise("Median" = median(value, na.rm = T))
medians <- medians[order(medians$Median, decreasing = T),]
tpm.melted$variable <- factor(tpm.melted$variable, levels = as.character(medians$variable))
all <- ggplot(tpm.melted, aes(x = variable, y = value)) + geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#Protein coding genes
load(CORUM_feat_tissue_general_path)
tpm <- datasets$scaled.GTEx.v8.TPM
tpm <- tpm[tpm$Gene.name %in% gene.table$Gene.name,]
tpm.melted <- melt(tpm)
medians <- tpm.melted %>% group_by(variable) %>% summarise("Median" = median(value, na.rm = T))
medians <- medians[order(medians$Median, decreasing = T),]
tpm.melted$variable <- factor(tpm.melted$variable, levels = as.character(medians$variable))
pc <- ggplot(tpm.melted, aes(x = variable, y = value)) + geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
