---
title: "Classification based amplification and deletion scores"
output: html_document
date: "2026-02-10"
---

  
```{r setup, include=FALSE}
# Classification based amplification and deletion scores

# Required libraries
library(stringr)
library(parallel)
library(reshape2)
library(dplyr)
library(ggplot2)
library(ggpubr)

rm(list=ls())

# Set here the working directory
knitr::opts_knit$set(root.dir = "/Volumes/Crucial X9/gukguk/old_WS/gokce")

gc()
```

***1. Classification of segments***
```{r script1, include=FALSE}

# Cancer types
cohorts <- unlist(lapply(list.files("./Data/Mapping_SCNAs/temp4/"), function(x) strsplit(x,"_")[[1]][1]))

# 1.1. Length-based

# Segments shorter than 1 kbp were excluded. 
# Segments were classified as focal, mid length, arm level and chromosome level:
# (i) Chromosome level: If farm  .90 only for both arms; 
# (ii) Arm level: If farm  .90 for one arm only; 
# (iii) focal: If 1 kbp  sgl  3Mbp; 
# (iv) Mid length: all the other segments 
# where, sgl is segment length, and farm is arm-specific length fraction

# Definitions of cut-offs
# A. Segment classification
arm.fraction <- c(#0.5,0.8,
                  0.9)

for(armf in arm.fraction){
  source('./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/1.1_segment_classification.R', local = T, verbose = F)
}

# 1.2. Location-based (Continue with 11 cancer types)

# Focal and mid-length segments were further subdivided into four classes based on their location on the 
# corresponding chromosome arm: (1) Centromere bound, (2) Telomere bound, (3) Centromere spanning (specific # to mid-length segments only), and (4) Interstitial. 

rm(list = ls())

# Data from length-based classification
output.files <- list.files(path = "./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/Data/ClusterI", pattern = "armfraction", full.names = T,
                           recursive = F)

# Cohorts
cohorts <- c("BRCA","COADREAD","ESCA","GBMLGG","KIRC","KIRP","LUAD","LUSC","OV","PAAD","STAD")

# Cut-off for telomere/centromere distance
# Centromere
load("./Codes/Parameter_tuning_segments/Data/Centromere-turningpoints.RData")
centromere <- stat[stat$Cohort %in% cohorts & stat$Value == "Absolute",1:3]
centromere <- centromere %>% group_by(Chromosome) %>% summarise("Mean" = mean(TP1, na.rm = T))
# Telomere
load("./Codes/Parameter_tuning_segments/Data/Telomere-turningpoints.RData")
telomere <- stat[stat$Cohort %in% cohorts & stat$Value == "Absolute",1:3]
telomere <- telomere %>% group_by(Chromosome) %>% summarise("Mean" = mean(TP1, na.rm = T))

# Data with centromere and telomere distances of break points
load("./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/Data/Data_and_plots_dist_centromere_telomere_armratio.RData")

rm(list = setdiff(ls(),c("output.files","cohorts","centromere","telomere","Data")))

for(file in output.files){
  load(file) # Output.List
  armf <- gsub(".RData","",strsplit(basename(file),"_")[[1]][2])
  source('./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/1.2_segment_classification.R', local = T, verbose = F)
}

# 1.3. Clusters (Based on cluster I and cluster II, deciding on final clusters & Sample size for each cluster)
rm(list = ls())

output.files <- list.files(path = "./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/Data/ClusterII", pattern = "armfraction", full.names = T,
                           recursive = F)
for(file in output.files){
  load(file) # Output.List.new
  armf <- gsub(".RData","",strsplit(basename(file),"_")[[1]][2])
  source('./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/1.3_segment_classification.R', local = T, verbose = F)
}

```

  
***2. Identifying which bins are amplified or deleted based on segment clusters.***

***2.1. For each bin and sample, find the amplified, deleted and diploid fraction***
```{r script2.1, include=FALSE}

# Bin information, chromosome, start and end position for each bin at each level
rm(list = ls())
gc()

# Defining cutoff
# B. Identification of CNA events
# B.1. Segment Mean
seg.means <- c(0.2
               #,0.3
)

# Selected levels
levels <- c("0.1Mbp"
            #,"1Mbp","4Mbp"
            )

load("./Data/All_levels_backbonetables.RData")

# Segment files with segment classes - only go with the 90% arm fraction results

output.files <- list.files(path = "./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/Data/Final_clustering",
                           pattern = "armfraction", full.names = T,recursive = F)
output.files <- output.files[3] #90%

for(file in output.files){
  # Learn arm fraction cutoff
  armf <- strsplit(gsub(".RData","",basename(file)),"_")[[1]][2]
  load(file)
  tumor_types <- names(Cluster.data)
  for(segMean in seg.means){
    source('./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/2_identification_CNA_events_partI.R', local = T, verbose = F)
  }
}
```

***Middle step***
```{r script2.mid, include=FALSE}

# Middle step (to be used to count number of samples with segment info for the corresponding bin):
# Map segments to the bins only, to count the number of each segment class in each bin
# Bin information, chromosome, start and end position for each bin at each level

# Selected levels
levels <- c("0.1Mbp"
            #,"1Mbp","4Mbp"
            )

load("./Data/All_levels_backbonetables.RData")

# Segment files
output.files <- list.files(path = "./Data/Mapping_SCNAs/temp4", full.names = T, recursive = F,
                           pattern = "BRCA|COADREAD|ESCA|GBMLGG|KIRC|KIRP|LUAD|LUSC|OV|PAAD|STAD")

for(file in output.files){
  assign("scna.m",get(load(file)))
  rm(scna_w_armfraction)
  tumor_type <- strsplit(basename(file),"_")[[1]][1]
  source('./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/6_Segment_mapping.R', local = T, verbose = F)
}

```

***2.2. Based on bin coverage fraction patient-matrix and CNA frequencies***
```{r script2.2, include=FALSE}
# 2.2. Based on bin coverage fraction patient-matrix and CNA frequencies
# B.2. Coverage

rm(list = ls())
gc()

cov.threshold <- c(0,0.5,0.8) # No coutoff = 0
load("./Data/All_levels_backbonetables.RData")


# Segments clustered based on length on location
output.files <- list.files(path = "./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/CNA_fractions_per_sample_per_bin/Length_Location",
                           full.names = T, recursive = F)



for(covThr in cov.threshold){
  Results.data <- list()
  Results.data.totalCNA <- list()
  jobs <- length(output.files)
  for(file in output.files){
    # Learning the parameters from file name
    name <- gsub(".RData","",basename(file))
    tumor_type <- strsplit(name,"_")[[1]][1]
    level <- strsplit(name,"_")[[1]][2]
    
    sg.class <- paste(strsplit(name,"_")[[1]][4],strsplit(name,"_")[[1]][5],sep = "_")
    sg.class <- gsub("_Armfraction","",sg.class)
    
    # Segments clustered based on length on location
    if(sg.class %in% c("Arm-level","Chromosome-level")){
      armf <- strsplit(name,"_")[[1]][6]
      sg.mean <- strsplit(name,"_")[[1]][8]}
     else{
      armf <- strsplit(name,"_")[[1]][7]
      sg.mean <- strsplit(name,"_")[[1]][9]}
    
    
    # Bin, start and end locations
    coordinates <- do.call(rbind,chr_backbone_namesfixed[[level]])
    
    # Load the file
    load(file)
    source('./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/3_identification_CNA_events_partII.R', local = T, verbose = F)
    
    jobs <- jobs - 1
    print(jobs)
  }
  
  # If choosing segments clustered based on length on location
  file.path <- paste0("./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/Data/Patient_Matrix/Length_Location/Patient_bin_event_matrix","covThr_",covThr,".RData")
  save(Results.data, file = file.path)

  file.path <- paste0("./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/Data/Patient_Matrix/Length_Location/Patient_bin_event_matrix_totalCNA","covThr_",covThr,".RData")
  save(Results.data.totalCNA, file = file.path)
  
  
  rm(Results.data)
  rm(Results.data.totalCNA)
  gc()
  
}


```

***2.3. Amplification and deletion frequencies***
```{r script2.3, include=FALSE}
rm(list = ls())
gc()

# Data I: Segment clusters are based on length and location
files <- list.files(path = "./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/Data/Patient_Matrix/Length_Location",
                    full.names = TRUE, recursive = FALSE, pattern = "Patient_bin_event_matrix")
segment.classes <- c("Arm-level","Chromosome-level",
                     "Mid-length_Centromere-bounded","Mid-length_Centromere-spanning","Mid-length_Interstitial","Mid-length_Telomere-bounded",
                     "Small-scale_Interstitial","Small-scale_Centromere-bounded","Small-scale_Telomere-bounded")



cohorts <- c("BRCA","COADREAD","ESCA","GBMLGG","KIRC","KIRP","LUAD","LUSC","OV","PAAD","STAD")

for(file in files){
  
  if(grepl("totalCNA",basename(file)) == TRUE){
    covThr <- gsub(".RData","",strsplit(basename(file),"_")[[1]][6])
    event <- "TotalCNA"
  }else{
    covThr <- gsub(".RData","",strsplit(basename(file),"_")[[1]][5])
    event <- "ampl_or_del"
  }
  
  if(covThr == "0"){covThr <- "zero"}
  
  assign("Datasets",get(load(file)))
  suppressWarnings(rm(list = c("Results.data.totalCNA","Results.data")))
  gc()
  
  All.class.data <- list()
  
  for(level in c("0.1Mbp"
                 #,"1Mbp","4Mbp"
  )){
    for(segclass in segment.classes){
      All.classes <- c()
      for(cohort in cohorts){
        final.df <- Datasets[["ArmFraction_0.9"]][["SegMean_0.2"]][[level]][[segclass]][[cohort]]
        source('./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/4_CNA_frequencies.R', local = T, verbose = F)
      }
      All.class.data[[event]][[level]][[segclass]] <- All.classes
      print(segclass)
    }
  }
  
  res.path <- paste0("./Codes/Codes-CNAs/MethodII/Parameter_tuning_segments/Data/CNA_frequencies/Length_Location/",
                     "CNAFreq_11cohorts_covThr_",covThr,"_",event,"_divided_binsamples",".RData")
  save(All.class.data, file = res.path)
  
  
  rm(All.class.data)
  suppressWarnings(rm(list = c("Results.data.totalCNA","Results.data")))
  gc()
  
}

```
